/* Generated by cbindgen — do not edit by hand. */
/* Loom Sidecar FFI surface — Phase 51, Plan 01 */

#ifndef LOOM_SIDECAR_H
#define LOOM_SIDECAR_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Extract the sidecar overlay from a Parquet file.
 *
 * Opens the Parquet file at `file_path`, reads its metadata, and attempts to
 * extract a `"loom.sidecar.v1"` key-value entry.  On success, the encoded
 * overlay bytes are boxed and returned through `out_bytes`/`out_len`.
 * The caller must free the returned buffer via [`loom_sidecar_free_bytes`].
 *
 * # Returns
 *
 * * `0` — Sidecar found, bytes written to `out_bytes`/`out_len`.
 * * `1` — `file_path`, `out_bytes`, or `out_len` is null.
 * * `2` — File could not be opened or read.
 * * `3` — Sidecar data found but could not be decoded.
 * * `4` — Internal panic caught.
 * * `5` — No sidecar key found in the file's metadata.
 */
int32_t loom_sidecar_extract(const char *file_path, uint8_t **out_bytes, uintptr_t *out_len);

/**
 * Verify a sidecar overlay's L2Core IR and compute its content-hash identity.
 *
 * Decodes the overlay bytes, decodes the inner IR bytes into a
 * [`L2CoreProgram`], and computes the FNV-1a content-hash identity string.
 * The hash is returned as a null-terminated C string through `out_hash`.
 * The caller must free this string via `loom_sidecar_free_cstr`.
 *
 * # Returns
 *
 * * `0` — Overlay decoded and verified, hash written to `out_hash`.
 * * `1` — `overlay_bytes` or `out_hash` is null.
 * * `3` — Overlay or IR bytes are malformed/truncated.
 * * `4` — Internal panic caught.
 */
int32_t loom_sidecar_verify(const uint8_t *overlay_bytes,
                            uintptr_t overlay_len,
                            const char **out_hash);

/**
 * Evaluate the 4-gate sidecar routing decision.
 *
 * Decodes the overlay, verifies each chunk binding against the provided host
 * data bytes (if any), and runs the full routing gate.  The routing decision
 * is returned as a JSON string through `out_decision`.
 * The caller must free this string via `loom_sidecar_free_cstr`.
 *
 * # Returns
 *
 * * `0` — Routing decision computed, JSON written to `out_decision`.
 * * `1` — A required pointer argument is null.
 * * `3` — Overlay decode or routing failure.
 * * `4` — Internal panic caught.
 */
int32_t loom_sidecar_route(const uint8_t *overlay_bytes,
                           uintptr_t overlay_len,
                           const uint8_t *host_data,
                           uintptr_t host_data_len,
                           const char **out_decision);

/**
 * Free a byte buffer previously returned by [`loom_sidecar_extract`].
 *
 * Reconstructs the `Vec<u8>` from the pointer and length and drops it.
 * The caller must ensure `ptr` and `len` came from a prior call to
 * `loom_sidecar_extract` and that this function is called at most once
 * per allocation.
 *
 * # Returns
 *
 * * `0` — Buffer freed.
 * * `1` — `ptr` is null.
 */
int32_t loom_sidecar_free_bytes(uint8_t *ptr, uintptr_t len);

/**
 * Free a C string previously returned by [`loom_sidecar_verify`] or
 * [`loom_sidecar_route`].
 *
 * Reconstructs the `CString` from the raw pointer and drops it.  The caller
 * must ensure `ptr` came from a prior call to `loom_sidecar_verify` or
 * `loom_sidecar_route` and that this function is called at most once per
 * allocation.
 *
 * # Returns
 *
 * * `0` — String freed.
 * * `1` — `ptr` is null.
 */
int32_t loom_sidecar_free_cstr(char *ptr);

#endif  /* LOOM_SIDECAR_H */
