/* Generated by cbindgen — do not edit by hand. */
/* Loom Sidecar FFI surface — Phase 51, Plan 01 */

#ifndef LOOM_SIDECAR_H
#define LOOM_SIDECAR_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define LMC2_VERSION 1

#define EXPECTED_MLIR_MAJOR 22

typedef struct RuntimeAbiVersion RuntimeAbiVersion;



/**
 * Extract the sidecar overlay from a host file.
 *
 * Tries in order:
 * 1. External sidecar file at `<file_path>.loomsidecar` (production path).
 * 2. Embedded `"loom.sidecar.v1"` KeyValue metadata in Parquet metadata.
 *
 * On success, the encoded overlay bytes are boxed and returned through
 * `out_bytes`/`out_len`. The caller must free the returned buffer via
 * [`loom_free_bytes`].
 *
 * # Returns
 *
 * * `0` — Sidecar found, bytes written to `out_bytes`/`out_len`.
 * * `1` — `file_path`, `out_bytes`, or `out_len` is null.
 * * `2` — File could not be opened or read.
 * * `3` — Sidecar data found but could not be decoded.
 * * `4` — Internal panic caught.
 * * `5` — No sidecar found (neither external nor embedded).
 */
int32_t loom_extract(const char *file_path, uint8_t **out_bytes, uintptr_t *out_len);

/**
 * Verify a sidecar overlay's L2Core IR and compute its content-hash identity.
 *
 * Decodes the overlay bytes, runs full semantic verification of the inner
 * L2Core IR program via [`verify_l2_core_bytes`], and computes the FNV-1a
 * content-hash identity string. The hash is returned as a null-terminated
 * C string through `out_hash`. The caller must free this string via
 * `loom_free_cstr`.
 *
 * # Returns
 *
 * * `0` — Overlay decoded, IR semantically verified, hash written to `out_hash`.
 * * `1` — `overlay_bytes` or `out_hash` is null.
 * * `3` — Overlay or IR bytes are malformed/truncated.
 * * `6` — IR program failed semantic verification.
 * * `4` — Internal panic caught.
 */
int32_t loom_verify(const uint8_t *overlay_bytes, uintptr_t overlay_len, const char **out_hash);

/**
 * Evaluate the 4-gate sidecar routing decision.
 *
 * Decodes the overlay, verifies each chunk binding against the provided host
 * data bytes (if any), and runs the full routing gate.  The routing decision
 * is returned as a JSON string through `out_decision`.
 * The caller must free this string via `loom_free_cstr`.
 *
 * # Returns
 *
 * * `0` — Routing decision computed, JSON written to `out_decision`.
 * * `1` — A required pointer argument is null.
 * * `3` — Overlay decode or routing failure.
 * * `4` — Internal panic caught.
 */
int32_t loom_route(const uint8_t *overlay_bytes,
                   uintptr_t overlay_len,
                   const uint8_t *host_data,
                   uintptr_t host_data_len,
                   const char **out_decision);

/**
 * Verify a sidecar overlay's L2Core IR and return structured facts and
 * diagnostics as a JSON string.
 *
 * Decodes the overlay, runs full semantic verification via
 * [`verify_l2_core_bytes`], and emits a JSON object with the verification
 * result, content-hash identity, artifact facts, and diagnostic messages.
 * The JSON is returned as a null-terminated C string through `out_json`.
 * The caller must free this string via `loom_free_cstr`.
 *
 * # JSON schema
 *
 * ```json
 * {
 *   "accepted": true,
 *   "ir_hash": "blake3:...",
 *   "artifact_version": 1,
 *   "required_features": [],
 *   "input_ranges": [],
 *   "output_schema": [],
 *   "row_count_bound": 1024,
 *   "constraint_count": 0,
 *   "proof_obligation_count": 0,
 *   "diagnostics": []
 * }
 * ```
 *
 * # Returns
 *
 * * `0` — Verification completed, JSON written to `out_json`.
 * * `1` — A required pointer argument is null.
 * * `3` — Overlay or IR bytes are malformed/truncated.
 * * `4` — Internal panic caught.
 */
int32_t loom_verify_json(const uint8_t *overlay_bytes,
                         uintptr_t overlay_len,
                         const char **out_json);

/**
 * Decode a sidecar overlay and export the decoded columns as a single Arrow
 * C Data Interface **struct array**: one `ArrowSchema` + one `ArrowArray`
 * whose children are the output columns. This is the zero-copy boundary a
 * host engine (e.g. the DuckDB extension) uses to materialize typed rows.
 *
 * `out_schema` / `out_array` are pointers to caller-allocated C
 * `ArrowSchema` / `ArrowArray` structs (passed as `void*`). On success (`0`)
 * both are populated and the **caller owns them** — it must invoke each
 * struct's `release` callback per the Arrow C Data Interface contract. On any
 * non-success code the out structs are left untouched and the caller falls
 * back to a host-native reader.
 *
 * # Returns
 * * `0` — decoded; struct array written to the out pointers.
 * * `1` — a required pointer argument is null.
 * * `3` — overlay/IR malformed, or the program is not materializable.
 * * `4` — internal panic caught.
 * * `6` — the L2Core IR failed semantic verification.
 *
 * # Safety
 * `overlay_bytes`/`host_data` must be valid for their stated lengths;
 * `out_schema`/`out_array` must point to writable `ArrowSchema`/`ArrowArray`.
 */
int32_t loom_decode_carray(const uint8_t *overlay_bytes,
                           uintptr_t overlay_len,
                           const uint8_t *host_data,
                           uintptr_t host_data_len,
                           void *out_schema,
                           void *out_array);

/**
 * Decode a sidecar overlay through the full Loom execution loop.
 *
 * 1. Decodes the sidecar overlay and inner L2Core IR.
 * 2. Runs semantic verification.
 * 3. Evaluates the 4-gate routing decision.
 * 4. If Loom-native, runs the general L2Core interpreter and returns the
 *    decoded columns as a **bare Arrow IPC stream** through `out_ipc_bytes` /
 *    `out_ipc_len`. The buffer is a plain Arrow IPC stream (the encoding
 *    produced by `arrow_ipc::writer::StreamWriter`) with **no `LMA1`/`LMC2`
 *    container header** — consume it directly with `arrow_scan` / nanoarrow /
 *    `StreamReader` without unwrapping a Loom container.
 * 5. Returns routing+execution metadata as a JSON string through `out_json`.
 *
 * On any non-`loom-native` route (host-native fallback, verifier rejection,
 * unsupported encoding), `out_ipc_len` is `0` and the caller must use a
 * host-native reader. Always check the JSON `route` field before reading IPC.
 *
 * The caller must free both outputs: `loom_free_cstr` for the JSON,
 * `loom_free_bytes` for the IPC buffer (safe to call on a zero-length
 * buffer).
 *
 * # JSON schema
 *
 * ```json
 * {
 *   "route": "loom-native" | "host-native",
 *   "reason": "all-gates-passed" | "hash-mismatch" | "encoding-unsupported" | ...,
 *   "decode_status": "ok" | "unsupported" | "error",
 *   "ir_hash": "blake3:...",
 *   "row_count": 1024,
 *   "column_count": 1,
 *   "diagnostics": []
 * }
 * ```
 *
 * # Returns
 *
 * * `0` — Decode completed (check JSON `route` field for outcome).
 * * `1` — A required pointer argument is null.
 * * `3` — Overlay or IR bytes are malformed/truncated.
 * * `4` — Internal panic caught.
 */
int32_t loom_decode(const uint8_t *overlay_bytes,
                    uintptr_t overlay_len,
                    const uint8_t *host_data,
                    uintptr_t host_data_len,
                    const char **out_json,
                    uint8_t **out_ipc_bytes,
                    uintptr_t *out_ipc_len);

/**
 * Free a byte buffer previously returned by [`loom_extract`].
 *
 * Reconstructs the `Vec<u8>` from the pointer and length and drops it.
 * The caller must ensure `ptr` and `len` came from a prior call to
 * `loom_extract` and that this function is called at most once
 * per allocation.
 *
 * # Returns
 *
 * * `0` — Buffer freed.
 * * `1` — `ptr` is null.
 */
int32_t loom_free_bytes(uint8_t *ptr, uintptr_t len);

/**
 * Free a C string previously returned by [`loom_verify`] or
 * [`loom_route`].
 *
 * Reconstructs the `CString` from the raw pointer and drops it.  The caller
 * must ensure `ptr` came from a prior call to `loom_verify` or
 * `loom_route` and that this function is called at most once per
 * allocation.
 *
 * # Returns
 *
 * * `0` — String freed.
 * * `1` — `ptr` is null.
 */
int32_t loom_free_cstr(char *ptr);

#endif  /* LOOM_SIDECAR_H */
