/* Generated by cbindgen — do not edit by hand. */
/* Loom FFI surface — Phase 1, Plan 02 (CORE-03) */

#ifndef LOOM_H
#define LOOM_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/* Self-contained forward declarations for the Arrow C Data Interface structs. */
typedef struct ArrowArray FFI_ArrowArray;
typedef struct ArrowSchema FFI_ArrowSchema;

/**
 * Export a minimal Arrow array across the C Data Interface.
 *
 * # Parameters
 *
 * - `input_ptr` — pointer to the encoded input bytes (may be null only if
 *   `input_len` is 0).
 * - `input_len` — number of valid bytes at `input_ptr`.
 * - `out_array` — caller-allocated `FFI_ArrowArray` shell (must be non-null).
 * - `out_schema` — caller-allocated `FFI_ArrowSchema` shell (must be non-null).
 *
 * # Return value
 *
 * `0` on success; nonzero on error (see [`LoomError`]).
 *
 * # Safety
 *
 * The caller must ensure:
 * - `out_array` and `out_schema` point to caller-allocated, properly aligned,
 *   writeable memory for their respective types.
 * - `input_ptr` is either null (with `input_len == 0`) or points to at least
 *   `input_len` valid bytes.
 * - The written `FFI_ArrowArray` and `FFI_ArrowSchema` are eventually released
 *   by calling their respective `release` callbacks exactly once.
 */
int32_t loom_decode(const uint8_t *input_ptr,
                    uintptr_t input_len,
                    FFI_ArrowArray *out_array,
                    FFI_ArrowSchema *out_schema);

#endif  /* LOOM_H */
